-- 1. Setup Role
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS DQ_ENGINEER;
GRANT ROLE DQ_ENGINEER TO USER DATA2DOLLARS;

-- 2. System Grants for Native DMFs and Monitoring
USE ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE DQ_ENGINEER;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE DQ_ENGINEER;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE DQ_ENGINEER;
GRANT APPLICATION ROLE SNOWFLAKE.DATA_QUALITY_MONITORING_VIEWER TO ROLE DQ_ENGINEER;


-- 3. Warehouse and Database Grants
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DQ_ENGINEER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DQ_ENGINEER;


USE ROLE DQ_ENGINEER;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS DQ_DEMO_DB;
CREATE SCHEMA IF NOT EXISTS DQ_DEMO_DB.DQ_DATA;
CREATE SCHEMA IF NOT EXISTS DQ_DEMO_DB.DQ_FUNCTIONS;


USE DATABASE DQ_DEMO_DB;
USE SCHEMA DQ_DATA;

CREATE OR REPLACE TABLE CUSTOMER_ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID VARCHAR,
    AMOUNT NUMBER(10, 2),
    EMAIL VARCHAR,
    STATUS VARCHAR,
    ORDER_DATE TIMESTAMP_LTZ
);

INSERT INTO CUSTOMER_ORDERS VALUES
    (1001, 'CUST_01',  250.00, 'john@example.com',  'Completed', '2025-01-01 10:00:00'),
    (1002, 'CUST_02',  -50.00, 'alice_at_domain',   'PENDING',   '2025-01-02 11:30:00'), -- Invalid Email + Case format violation + Negative Amount
    (1003, NULL,         0.00, 'bob@company.org',   'Completed', '2030-12-31 00:00:00'), -- NULL Customer ID + Zero Amount + Future Timestamp
    (1001, 'CUST_01',  250.00, 'john@example.com',  'Completed', '2025-01-01 10:00:00'), -- Duplicate Row
    (1004, 'CUST_04', 99999.00, '  dave@corp.co ',  'processing', CURRENT_TIMESTAMP());  -- Outlier Amount + Untrimmed Email


USE SCHEMA DQ_DEMO_DB.DQ_FUNCTIONS;

-- Custom DMF 1: Check Email Format
CREATE OR REPLACE DATA METRIC FUNCTION INVALID_EMAIL_COUNT (
    ARG_T TABLE (ARG_C1 VARCHAR)
)
RETURNS NUMBER
AS 
$$
    SELECT COUNT(*) 
    FROM ARG_T 
    WHERE ARG_C1 NOT REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$' 
       OR ARG_C1 IS NULL
$$;


-- Custom DMF 2: Check Invalid Order Amounts
CREATE OR REPLACE DATA METRIC FUNCTION NON_POSITIVE_AMOUNT_COUNT (
    ARG_T TABLE (ARG_C1 NUMBER)
)
RETURNS NUMBER
AS 
$$
    SELECT COUNT(*) 
    FROM ARG_T 
    WHERE ARG_C1 <= 0 OR ARG_C1 IS NULL
$$;

USE DATABASE DQ_DEMO_DB;
USE SCHEMA DQ_DATA;

ALTER TABLE CUSTOMER_ORDERS SET DATA_METRIC_SCHEDULE = '5 MINUTE';
-- 3. ATTACH CUSTOM BUSINESS LOGIC DMFs
-- -------------------------------------------------------------
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION DQ_DEMO_DB.DQ_FUNCTIONS.INVALID_EMAIL_COUNT ON (EMAIL);
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION DQ_DEMO_DB.DQ_FUNCTIONS.NON_POSITIVE_AMOUNT_COUNT ON (AMOUNT);


-- -------------------------------------------------------------
-- 4. ATTACH NATIVE SNOWFLAKE SYSTEM DMFs (SNOWFLAKE.CORE.*)
-- -------------------------------------------------------------

-- Accuracy / Completeness Checks
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);

-- Add Expectation: Fail if null count exceeds 10
ALTER TABLE CUSTOMER_ORDERS MODIFY DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID) ADD EXPECTATION no_nulls_in_id (VALUE <= 10);


    
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);

-- Zero & Value Validation
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ZERO_COUNT ON (AMOUNT);

-- Casing & Whitespace Quality Checks
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.CASE_FORMAT_VIOLATION_COUNT ON (STATUS);
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.UNTRIMMED_STRING_COUNT ON (EMAIL);

-- Timestamp & Freshness Checks
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FUTURE_TIMESTAMP_COUNT ON (ORDER_DATE);
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (ORDER_DATE);

-- Statistical Outlier Checks
ALTER TABLE CUSTOMER_ORDERS ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.OUTLIER_IQR_COUNT ON (AMOUNT);

-- Check active schedules on table
SHOW PARAMETERS LIKE 'DATA_METRIC_SCHEDULE' IN TABLE DQ_DEMO_DB.DQ_DATA.CUSTOMER_ORDERS;


-- See all DMFs assigned to the table
SELECT * 
FROM TABLE(INFORMATION_SCHEMA.DATA_METRIC_FUNCTION_REFERENCES(
    REF_ENTITY_NAME => 'DQ_DEMO_DB.DQ_DATA.CUSTOMER_ORDERS',
    REF_ENTITY_DOMAIN => 'TABLE'
));


-- Query scheduled evaluation results (Real-Time Local Log)
SELECT 
    SCHEDULED_TIME,
    MEASUREMENT_TIME,
    TABLE_NAME,
    METRIC_NAME,
    ARGUMENT_NAMES,
    VALUE
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE TABLE_NAME = 'CUSTOMER_ORDERS'
ORDER BY MEASUREMENT_TIME DESC;


-- Query Account Usage History for Serverless Credit Usage (1–2 hr latency)
SELECT 
    *
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_QUALITY_MONITORING_USAGE_HISTORY
WHERE START_TIME >= CURRENT_TIMESTAMP() - INTERVAL '7 DAYS'
ORDER BY START_TIME DESC;


